;;;; src/package.lisp

(defpackage #:cl-boundary-kit
  (:use #:cl)
  (:export
   #:make-boundary-context
   #:boundary-context-get
   #:boundary-context-present-p
   #:make-recording-boundary
   #:recording-boundary-calls
   #:recording-boundary-invoke
   #:unsupported-boundary-operation
   #:unsupported-boundary-operation-operation
   #:unsupported-boundary-operation-detail
   #:make-filesystem
   #:filesystem-read-file
   #:filesystem-store-file
   #:filesystem-probe-file
   #:filesystem-list-directory
   #:filesystem-path-exists-p
   #:make-test-filesystem
   #:make-recording-filesystem
   #:recording-filesystem-calls
   #:make-environment
   #:environment-get
   #:environment-present-p
   #:environment-set
   #:environment-list
   #:make-test-environment
   #:make-recording-environment
   #:recording-environment-calls
   #:make-clock
   #:clock-now
   #:clock-monotonic
   #:make-fake-clock
   #:advance-fake-clock
   #:make-random-source
   #:make-deterministic-random-source
   #:make-test-random-source
   #:random-source-random
   #:make-process-boundary
   #:make-test-process-boundary
   #:process-boundary-run
   #:make-recording-process-boundary
   #:recording-process-calls
   #:make-network-boundary
   #:make-test-network-boundary
   #:network-boundary-request
   #:make-recording-network-boundary
   #:recording-network-calls
   #:make-logger
   #:make-test-logger
   #:logger-log
   #:make-recording-logger
   #:recording-log-events
   #:assert-recorded-call
   #:assert-recorded-call-count
   #:assert-recorded-call-sequence
   #:boundary-call-plist))
